import crypto from 'node:crypto'
import os from 'node:os'
import path from 'node:path'
import fs from 'fs-extra'
import { afterEach, describe, expect, it } from 'vitest'
import { generateRobotsTxt, ROBOTS_FILE_NAME, writeRobotsFile } from '../../../lib/robots.ts'

let tmpDir: string | undefined

function createTmpDir() {
  tmpDir = path.join(os.tmpdir(), `robots-test-${crypto.randomUUID()}`)
  return tmpDir
}

afterEach(async () => {
  if (tmpDir)
    await fs.remove(tmpDir)
  tmpDir = undefined
})

describe('generateRobotsTxt', () => {
  it('disallows every crawler by default', () => {
    expect(generateRobotsTxt(false)).toBe('# Generated by kss-modern\nUser-agent: *\nDisallow: /\n')
  })

  it('allows every crawler when indexing is enabled', () => {
    expect(generateRobotsTxt(true)).toBe('# Generated by kss-modern\nUser-agent: *\nAllow: /\n')
  })
})

describe('writeRobotsFile', () => {
  it('writes robots.txt into the output root', async () => {
    const outDir = createTmpDir()
    await writeRobotsFile(outDir, false)

    const content = await fs.readFile(path.join(outDir, ROBOTS_FILE_NAME), 'utf-8')
    expect(content).toContain('Disallow: /')
  })

  it('overwrites an existing robots.txt when the option changes', async () => {
    const outDir = createTmpDir()
    await writeRobotsFile(outDir, false)
    await writeRobotsFile(outDir, true)

    const content = await fs.readFile(path.join(outDir, ROBOTS_FILE_NAME), 'utf-8')
    expect(content).toContain('Allow: /')
    expect(content).not.toContain('Disallow: /')
  })
})
