import path from 'node:path'
import { logicalWriteFile } from './utils.ts'

/** The file name written into the output directory's root. */
export const ROBOTS_FILE_NAME = 'robots.txt'

/**
 * The `robots.txt` body for a styleguide.
 *
 * A styleguide is internal documentation for a team, so indexing is off unless the styleguide
 * asks for it. `Disallow: /` keeps crawlers out of the whole output directory, including the
 * fullpage previews and the generated assets. The matching `<meta name="robots">` in every page
 * is what actually keeps an already-known URL out of the result list, since a disallowed page
 * can still be listed when something links to it.
 */
export function generateRobotsTxt(allowSearchEngineIndexing: boolean): string {
  const rule = allowSearchEngineIndexing ? 'Allow: /' : 'Disallow: /'

  return `# Generated by kss-modern\nUser-agent: *\n${rule}\n`
}

/** Write `robots.txt` into the output directory's root. */
export async function writeRobotsFile(outDir: string, allowSearchEngineIndexing: boolean): Promise<void> {
  await logicalWriteFile(path.join(outDir, ROBOTS_FILE_NAME), generateRobotsTxt(allowSearchEngineIndexing))
}
